var PROGRAMS = [
  { name: "python", desc: "Python interpreter" },
  { name: "node", desc: "Node.js runtime" },
  { name: "deno", desc: "Deno runtime" },
  { name: "git", desc: "Version control" },
  { name: "vim", desc: "Modal editor" },
  { name: "nano", desc: "Simple editor" },
  { name: "code", desc: "VS Code" },
  { name: "npm", desc: "Node package manager" },
  { name: "pnpm", desc: "Fast package manager" },
  { name: "cargo", desc: "Rust toolchain" },
  { name: "make", desc: "Build tool" },
  { name: "curl", desc: "HTTP client" },
  { name: "ssh", desc: "Remote shell" },
  { name: "grep", desc: "Search text" },
  { name: "less", desc: "Pager" },
  { name: "top", desc: "Process monitor" },
  { name: "preview", desc: "File previewer" },
];
